Repository immich-app/ui, pull requests merged in 2025-01, with the labels that each got.

#60 feat: closable alerts
  src/lib/components/Alert/Alert.svelte
  src/routes/components/alert/+page.svelte
  src/routes/components/alert/EventExample.svelte
Labels: changelog:feature

#61 feat: alert sizes
  src/lib/components/Alert/Alert.svelte
  src/routes/components/alert/BasicExample.svelte
Labels: changelog:feature

#66 feat: theme switcher component
  scripts/create.js
  src/docs/constants.ts
  src/lib/components/ThemeSwitcher/ThemeSwitcher.svelte
  src/lib/index.ts
  src/routes/components/theme-switcher/+page.svelte
  src/routes/components/theme-switcher/BasicExample.svelte
  src/routes/components/theme-switcher/SizeExample.svelte
  src/routes/components/theme-switcher/VariantExample.svelte
Labels: changelog:feature

#68 feat: kbd component
  src/docs/constants.ts
  src/lib/components/Kbd/Kbd.svelte
  src/lib/index.ts
  src/routes/components/kbd/+page.svelte
  src/routes/components/kbd/BasicExample.svelte
  src/routes/components/kbd/SizeExample.svelte
Labels: changelog:feature

#71 feat: translations
  src/lib/components/CloseButton/CloseButton.svelte
  src/lib/components/Form/PasswordInput.svelte
  src/lib/index.ts
  src/lib/services/translation.svelte.ts
  src/lib/types.ts
  src/routes/components/close-button/+page.svelte
  src/routes/components/close-button/TranslationExample.svelte
  src/routes/components/password-input/+page.svelte
  src/routes/components/password-input/BasicExample.svelte
  src/routes/components/password-input/TranslationExample.svelte
Labels: changelog:feature

#74 fix: heading props
  src/lib/components/Heading/Heading.svelte
Labels: changelog:bugfix

#73 fix: theme switcher color
  src/lib/components/ThemeSwitcher/ThemeSwitcher.svelte
  src/routes/components/theme-switcher/+page.svelte
  src/routes/components/theme-switcher/ColorExample.svelte
  src/routes/components/theme-switcher/SizeExample.svelte
Labels: changelog:bugfix

#77 fix: code filled primary color
  src/lib/components/Code/Code.svelte
Labels: changelog:bugfix

#78 chore: Card/IconButton/Button minor tweak
  src/lib/components/Card/Card.svelte
  src/lib/components/IconButton/IconButton.svelte
  src/lib/internal/Button.svelte
Labels: changelog:enhancement

#79 fix: tweaks
  src/lib/components/Code/Code.svelte
  src/lib/components/Form/Field.svelte
  src/lib/components/Form/Input.svelte
  src/routes/components/select/BasicExample.svelte
  src/routes/components/switch/FormExample.svelte
Labels: changelog:bugfix

#81 feat: app shell improvements
  src/docs/components/Footer.svelte
  src/lib/components/AppShell/AppShell.svelte
  src/lib/components/AppShell/AppShellSidebar.svelte
  src/lib/components/Modal/Modal.svelte
  src/lib/components/Navbar/NavbarGroup.svelte
  src/lib/components/Navbar/NavbarItem.svelte
  src/lib/components/Scrollable/Scrollable.svelte
  src/routes/+layout.svelte
  src/routes/components/navbar/+page.svelte
  src/routes/components/navbar/VariantExample.svelte
  static/img/social-preview.webp
Labels: changelog:feature

#83 feat: default is-active logic
  src/lib/components/Navbar/NavbarItem.svelte
  src/routes/+layout.svelte
Labels: changelog:enhancement

#88 fix: modal events
  src/lib/components/AppShell/AppShellSidebar.svelte
  src/lib/components/Modal/Modal.svelte
  src/routes/components/modal/+page.svelte
  src/routes/components/modal/RouteExample.svelte
Labels: changelog:bugfix

#90 fix: card background
  src/lib/components/Card/Card.svelte
Labels: changelog:bugfix

#91 feat: buttons with icons
  src/docs/components/ComponentExampleCard.svelte
  src/lib/internal/Button.svelte
  src/lib/types.ts
  src/routes/components/button/+page.svelte
  src/routes/components/button/IconExample.svelte
  src/routes/components/button/LinkExample.svelte
Labels: changelog:feature

#92 fix: modal escape event
  package-lock.json
  src/lib/components/Modal/Modal.svelte
  src/routes/components/modal/BasicExample.svelte
  src/routes/components/modal/SizeExample.svelte
Labels: changelog:bugfix

#95 feat: container component
  src/docs/components/ComponentPage.svelte
  src/docs/components/Footer.svelte
  src/docs/constants.ts
  src/lib/components/Container/Container.svelte
  src/lib/index.ts
  src/lib/types.ts
  src/routes/+page.svelte
  src/routes/components/container/+page.svelte
  src/routes/components/container/BasicExample.svelte
  src/routes/components/container/CenterExample.svelte
Labels: changelog:feature

#94 feat: better labels
  src/lib/common/context.svelte.ts
  src/lib/components/Form/Checkbox.svelte
  src/lib/components/Form/Field.svelte
  src/lib/components/Form/Input.svelte
  src/lib/components/Form/Label.svelte
  src/lib/components/Form/PasswordInput.svelte
  src/lib/components/IconButton/IconButton.svelte
  src/lib/components/Label/Label.svelte
  src/lib/components/Switch/Switch.svelte
  src/lib/index.ts
  src/lib/internal/Button.svelte
  src/lib/internal/Select.svelte
  src/lib/styles.ts
  src/lib/types.ts
  src/routes/components/field/+page.svelte
  src/routes/components/field/ColorExample.svelte
  src/routes/components/switch/FormExample.svelte
Labels: changelog:feature
