Repository immich-app/ui, pull requests merged in 2025-08, with the labels that each got.

#226 fix: modal race conditions
  src/lib/services/modalManager.svelte.ts
Labels: changelog:bugfix

#230 fix: modal race conditions (again...)
  src/lib/services/modalManager.svelte.ts
Labels: changelog:bugfix

#229 crop playstore badge to match other badges
  src/lib/assets/playstore-badge.png
Labels: changelog:enhancement

#242 fix: button cursor
  src/lib/internal/Button.svelte
Labels: changelog:bugfix

#246 fix: input button
  src/lib/components/Form/Input.svelte
Labels: changelog:bugfix

#249 feat: custom modal header
  src/lib/components/Button/Button.svelte
  src/lib/components/Card/Card.svelte
  src/lib/components/Modal/Modal.svelte
  src/lib/index.ts
  src/routes/components/modal/IconExample.svelte
Labels: changelog:feature
